- hosts: crane
  become: true
  become_user: root
  tasks:
    - name: install firewalld
      apt: state=present name=firewalld
    #
    # Zone public (wlan0)
    #
    - name: configure firewall zone public
      firewalld: zone=public interface=wlan0 permanent=yes immediate=yes state=enabled
    - name: disable ssh on public zone
      firewalld: zone=public service=ssh permanent=yes immediate=yes state=disabled
    #
    # Zone home (eth0)
    # 
    - name: configure firewall zone home
      firewalld: zone=home interface=eth0 permanent=yes immediate=yes state=enabled
    - name: enable mosquitto (1883) on home zone
      firewalld: zone=home port=1883/tcp permanent=yes immediate=yes state=enabled
    - name: enable mosquitto encrypted (8883) on home zone
      firewalld: zone=home port=8883/tcp permanent=yes immediate=yes state=enabled
    - name: enable openhab webui (8443) on home zone
      firewalld: zone=home port=8443/tcp permanent=yes immediate=yes state=enabled

