- hosts: crane
  remote_user: pi
  become_user: root
  become: yes
  tasks:
    - name: setup wpa_supplicant
      copy: src=files/wpa_supplicant.conf dest=/etc/wpa_supplicant/wpa_supplicant.conf mode=0600 owner=root group=root
    - name: stop wlan0
      command: ifdown wlan0
    - name: start wlan0
      command: ifup wlan0
    - name: sleep
      command: sleep 10
    - name: install zsh and sudo
      apt: name=zsh,sudo state=present update_cache=yes
    - name: add grml zsh config
      get_url: url=http://git.grml.org/f/grml-etc-core/etc/zsh/zshrc dest=/etc/zsh/zshrc
    - name: allow wheel group to use sudo
      lineinfile: "dest=/etc/sudoers state=present regexp='^%wheel' line='%wheel ALL=(ALL) NOPASSWD: ALL'"
    - name: add wheel group
      group: name=wheel state=present
    - name: add user jb
      user: name=jb shell=/bin/zsh state=present createhome=yes groups=users,wheel
    - name: add empty zshrc for jb
      file: path=/home/jb/.zshrc owner=jb group=jb state=touch
    - name: add public key jb
      authorized_key: user=jb key="{{ item }}" state=present
      with_file:
        - public_keys/jb.pub
    - name: add user domfi
      user: name=domfi shell=/bin/bash state=present createhome=yes groups=users,wheel
    - name: add public key domfi
      authorized_key: user=domfi key="{{ item }}" state=present
      with_file:
        - public_keys/domfi.pub
