- hosts: crane
  tasks:
    - name: set hostname
      become: true
      become_user: root
      hostname: name=crane.chaos-consulting.de
    - name: create openhab group
      become: true
      become_user: root
      group: state=present name=openhab
    - name: create openhab user
      become: true
      become_user: root
      user: state=present name=openhab home=/opt/openhab/ group=openhab
    - name: add users to openhab group
      become: true
      become_user: root
      user: name={{ item }} append=yes groups=openhab state=present
      with_items:
        - pi
        - jb
        - domfi
    - name: allow all openhab members to become openhab user
      become: true
      become_user: root
      lineinfile: "dest=/etc/sudoers state=present regexp='^%openhab' line='%openhab ALL=(ALL) NOPASSWD: ALL'"
    - name: fetch openHAB installation files
      become: true
      become_user: openhab
      unarchive:
        src: https://openhab.ci.cloudbees.com/job/openHAB-Distribution/lastSuccessfulBuild/artifact/distributions/openhab-offline/target/openhab-offline-2.0.0-SNAPSHOT.zip
        dest: /opt/openhab
        group: openhab
        mode: g+w
        copy: no
        creates: /opt/openhab/start.sh
      

- hosts: crane
  become: true
  become_user: root
  tasks:
    - name: add key for mosquitto repo
      apt_key: url=http://repo.mosquitto.org/debian/mosquitto-repo.gpg.key state=present
    - name: add alternative mosquitto repo
      apt_repository: repo='deb http://repo.mosquitto.org/debian wheezy main' state=present
    - name: install mosquitto
      apt: state=latest name=mosquitto
    - name: install mosquitto-clients
      apt: state=latest name=mosquitto-clients
    - name: install libmosquitto1
      apt: state=latest name=libmosquitto1
    #
    # Firewall setup
    #
    - name: install firewalld
      apt: state=present name=firewalld
    - name: configure firewall zone home
      firewalld: zone=home interface=eth0 permanent=yes immediate=yes state=enabled
    - name: configure firewall zone public
      firewalld: zone=public interface=wlan0 permanent=yes immediate=yes state=enabled
    - name: disable ssh on public zone
      firewalld: zone=public service=ssh permanent=yes immediate=yes state=disabled 
    - name: enable mosquitto (1883) on home zone
      firewalld: zone=home port=1883/tcp permanent=yes immediate=yes state=enabled
    - name: enable mosquitto encrypted (8883) on home zone
      firewalld: zone=home port=8883/tcp permanent=yes immediate=yes state=enabled
    - name: enable openhab webui (8443) on home zone
      firewalld: zone=home port=8443/tcp permanent=yes immediate=yes state=enabled
