---

- name: install openhab dependencies
  apt: name=rsync,oracle-java8-jdk,apt-transport-https state=present
- name: add openhab gpg key
  apt_key: url=https://bintray.com/user/downloadSubjectPublicKey?username=openhab state=present
- name: add openhab2 repo
  apt_repository: repo="deb https://dl.bintray.com/openhab/apt-repo2 stable main" filename=openhab2 state=present
- name: install openhab2
  apt: name=openhab2 state=latest update_cache=true
- name: add configuration
  synchronize: src=files/conf/openhab2 dest=/etc/ owner=no group=no
- include_vars: "{{inventory_hostname}}.yml"
- name: add templates
  template: src=templates/openhab/{{ item.src }} dest=/etc/openhab2/{{ item.dest }} owner=openhab group=openhab
  with_items:
    - { src: "mqtt1.cfg.j2", dest: "services/mqtt1.cfg" }
    - { src: "telegram.cfg.j2", dest: "services/telegram.cfg" }
- name: use openhab user/group for configuration files
  file: dest=/etc/openhab2 owner=openhab group=openhab recurse=yes
- name: enable openhab2 service
  service: name=openhab2 enabled=yes state=started
